const SEED_CARDS = [
  // ── HISTORY (17) ─────────────────────────────────────────────────────────

  {
    format: 'story',
    hook: 'De bibliotheek van Alexandria verbrandde nooit op één nacht.',
    body: 'Het populaire beeld: één catastrofale brand vernietigde alle kennis van de oudheid. De werkelijkheid is anders. De bibliotheek raakte eeuwenlang langzaam in verval — door bezuinigingen, vertrek van geleerden en kleine incidenten. Julius Caesar, Theophilus en de Arabieren werden allemaal beschuldigd, maar historici vinden voor geen van hen sluitend bewijs. De kennis ging niet verloren door vuur, maar door verwaarlozing.',
    keyInsight: 'Beschaving vergaat zelden door één dramatische klap, maar door duizend kleine nalatigheden.',
    domain: 'history',
    topics: ['oudheid', 'mythes', 'kennisoverdracht'],
  },
  {
    format: 'insight',
    hook: 'Vikingen droegen geen gehoornd helm — dat is een negentiende-eeuwse fantasie.',
    body: 'Geen enkele opgegraven Vikinghelm heeft hoorns. Het beeld komt grotendeels van een operakostuum dat de Zweedse schilder August Malmström in 1876 ontwierp voor een productie van Wagner. Romantische nationalisten grepen het beeld gretig aan. De échte Vikinghelm was een simpele ijzeren pot met een neusplaat — functioneel, niet theatraal.',
    keyInsight: 'Veel van wat we "weten" over het verleden is negentiende-eeuwse romantische projectie.',
    domain: 'history',
    topics: ['vikingen', 'mythes', 'populaire cultuur'],
  },
  {
    format: 'contrast',
    hook: 'Slavernij werd afgeschaft omdat mensen het immoreel vonden.',
    body: 'Slavernij was altijd al immoreel, en velen wisten dat || Abolitionisme triomfeerde pas toen slavernij economisch minder rendabel werd én een georganiseerde beweging politieke druk opbouwde. Economen als Robert Fogel toonden aan dat plantageslavernij winstgevend was tot het einde. Morele overtuiging was nodig maar niet voldoende — structurele economische verschuivingen en massabeweging maakten het verschil.',
    keyInsight: 'Morele vooruitgang vereist meer dan goede ideeën: het vraagt ook economische druk en georganiseerde actie.',
    domain: 'history',
    topics: ['slavernij', 'abolitionisme', 'morele geschiedenis'],
  },
  {
    format: 'story',
    hook: 'Een vrouw redde duizenden levens door één fout in een handboek te ontdekken.',
    body: 'In 1961 weigerde FDA-functionaris Frances Kelsey toestemming voor thalidomide in de VS. Fabrikanten noemden haar moeilijk en koppig. Maanden later bleek dat thalidomide ernstige aangeboren afwijkingen veroorzaakte bij duizenden Europese baby\'s. Kelsey\'s hardnekkigheid redde Amerika van dezelfde ramp. Ze ontving de hoogste Amerikaanse civiele onderscheiding. Haar verhaal leidde tot strengere medicijntesten wereldwijd.',
    keyInsight: 'Institutionele obstakels die irritant lijken, beschermen ons soms tegen catastrofes die we niet zien aankomen.',
    domain: 'history',
    topics: ['geneeskunde', 'regulering', 'vrouwen in wetenschap'],
  },
  {
    format: 'question',
    hook: 'Wat als de Zwarte Dood de Europese arbeider rijker maakte?',
    body: 'De pest van 1347–1353 doodde een derde tot de helft van de Europese bevolking. Dat klinkt als pure ramp. Maar historici ontdekten een onverwacht gevolg: door arbeidstekort steeg het loon van overlevende boeren dramatisch. Huurders konden voor het eerst onderhandelen. Feodale structuren brokkelden af. Sommige economisch-historici noemen de pest een cruciale versneller van het einde van het feodalisme.',
    keyInsight: 'Catastrofes kunnen bestaande machtsstructuren doorbreken op manieren die geleidelijke hervormingen nooit kunnen.',
    domain: 'history',
    topics: ['middeleeuwse geschiedenis', 'pest', 'economische gevolgen'],
  },
  {
    format: 'insight',
    hook: 'De eerste programmeur ooit was een negentiende-eeuwse vrouw.',
    body: 'Ada Lovelace schreef in 1843 het eerste algoritme dat bedoeld was voor een machine — de Analytische Machine van Charles Babbage, die nooit werd gebouwd. Ze begreep iets wat Babbage zelf niet volledig zag: dat de machine niet alleen kon rekenen, maar ook symbolen kon manipuleren. Ze beschreef lussen en vertakkingen. Haar aantekeningen werden een eeuw later herontdekt door computerpioniers.',
    keyInsight: 'Revolutionaire ideeën verschijnen soms decennia voor de technologie die ze mogelijk maakt.',
    domain: 'history',
    topics: ['technologie', 'vrouwen in wetenschap', 'computing'],
  },
  {
    format: 'story',
    hook: 'Napoleon was niet klein — dat is een Britse propagandatruc.',
    body: 'Napoleon mat 1,69 meter — gemiddeld voor zijn tijd. De verwarring ontstond door twee dingen: zijn bijnaam "le petit caporal" was een affectueuze term van zijn soldaten, niet een beschrijving van zijn lengte. Britse cartoonist James Gillray tekende hem consequent als dwerg om hem belachelijk te maken. Die karikaturen verspreidden zich zo wijd dat het beeld bleef hangen, lang na zijn dood.',
    keyInsight: 'Propaganda die vermakelijk genoeg is, wordt uiteindelijk als historisch feit geaccepteerd.',
    domain: 'history',
    topics: ['napoleon', 'propaganda', 'mythes'],
  },
  {
    format: 'contrast',
    hook: 'Christoffel Columbus bewees dat de aarde rond was.',
    body: 'Geleerde Europeanen wisten al eeuwen dat de aarde rond was || Het echte geschil was over de grootte van de aarde. Columbus dacht dat Azië veel dichterbij was dan het werkelijk is. Zijn tegenstanders hadden gelijk wat betreft de afstanden. Columbus had simpelweg geluk dat er een onbekend continent in de weg lag — anders was zijn bemanning omgekomen van dorst en honger.',
    keyInsight: 'Sommige historische "helden" slaagden niet dankzij hun gelijk, maar ondanks hun ongelijk.',
    domain: 'history',
    topics: ['ontdekkingsreizen', 'columbus', 'mythes'],
  },
  {
    format: 'question',
    hook: 'Hadden we de Tweede Wereldoorlog kunnen voorkomen met betere economie?',
    body: 'Econoom John Maynard Keynes schreef in 1919 "The Economic Consequences of the Peace" en voorspelde nauwkeurig dat de vernederende herstelbetalingen van Versailles Duitsland zouden destabiliseren. Zijn collega\'s negeerden hem. Herstelbetalingen, hyperinflatie en de Grote Depressie creëerden precies de wanhoop die Hitler politiek mogelijk maakte. Soms is de slechtste vrede een stap naar de volgende oorlog.',
    keyInsight: 'Economische vernedering na conflict zaait de zaden voor het volgende conflict.',
    domain: 'history',
    topics: ['tweede wereldoorlog', 'versailles', 'economie en oorlog'],
  },
  {
    format: 'insight',
    hook: 'De Berlijnse Muur viel door een persconferentie-vergissing.',
    body: 'Op 9 november 1989 las DDR-woordvoerder Günter Schabowski nieuwe reisregels voor op een persconferentie. Hij had de briefing gemist: de regels gingen pas de volgende dag in. Een journalist vroeg: "Wanneer geldt dit?" Schabowski aarzelde en zei: "Onmiddellijk, onverwijld." Binnen uren stroomden duizenden Berlijners naar de grens. Grenswachten, overweldigd en zonder orders, lieten hen door.',
    keyInsight: 'Historische keerpunten hangen soms af van miscommunicatie, verwarring en één foutief woord.',
    domain: 'history',
    topics: ['koude oorlog', 'berlijnse muur', 'duitsland'],
  },
  {
    format: 'story',
    hook: 'Eén Russische officier voorkwam eigenhandig de Derde Wereldoorlog.',
    body: 'Op 26 september 1983 detecteerde het Sovjet vroegwaarschuwingssysteem vijf inkomende Amerikaanse raketten. Luitenant-kolonel Stanislav Petrov had opdracht om direct te rapporteren — wat zou leiden tot een tegenaanval. Hij aarzelde: vijf raketten leek te weinig voor een echte eerste aanval. Hij meldde het als systeemfout. Hij had gelijk. Het was een storing. Zijn keuze om protocol te negeren voorkwam mogelijk nucleaire oorlog.',
    keyInsight: 'De veiligste momenten in de geschiedenis waren soms die waarop één persoon besloot de regels te negeren.',
    domain: 'history',
    topics: ['koude oorlog', 'nucleaire dreiging', 'individuele keuze'],
  },
  {
    format: 'contrast',
    hook: 'De middeleeuwse mens dacht dat de aarde plat was.',
    body: 'Middeleeuwse geleerden wisten vrijwel unaniem dat de aarde rond was || Ze baseerden zich op Aristoteles en Ptolemaeus, die de omtrek al in de oudheid hadden berekend. De "platte aarde" mythe werd in de negentiende eeuw gecreëerd door auteurs als John William Draper om een conflict te suggereren tussen wetenschap en religie — een conflict dat voor de middeleeuwen niet bestond zoals wij het ons voorstellen.',
    keyInsight: 'De "religieuze middeleeuwen vs. verlichte wetenschap" tegenstelling is grotendeels een negentiende-eeuwse uitvinding.',
    domain: 'history',
    topics: ['middeleeuwen', 'wetenschapsgeschiedenis', 'mythes'],
  },
  {
    format: 'story',
    hook: 'Een telefoonbedrijf dat begon als papiermolen domineerde de wereld.',
    body: 'Nokia begon in 1865 als papiermolen, stapte over op rubber en kabels, en belandde in de jaren tachtig bijna in faillissement. Toenmalig CEO Kari Kairamo pleegde zelfmoord onder de druk. Zijn opvolger Jorma Ollila nam een weddenschapje: alles inzetten op mobiele telefonie. In de jaren negentig domineerde Nokia 40% van de wereldmarkt. Daarna miste het de smartphone-revolutie — weer door één fatale strategische blindheid.',
    keyInsight: 'Bedrijfssuccessen zijn vaak het resultaat van existentiële crises gevolgd door gedwongen keuzes.',
    domain: 'history',
    topics: ['technologie', 'nokia', 'bedrijfsgeschiedenis'],
  },
  {
    format: 'insight',
    hook: 'Democratie werd in Athene uitgevonden om een burgeroorlog te stoppen.',
    body: 'Cleisthenes introduceerde in 508 v.Chr. democratische hervormingen niet uit idealisme, maar als politieke zet om zijn rivalen te verslaan. Hij mobiliseerde het gewone volk als tegenmacht tegen de aristocraten die hem hadden verbannen. Democratie als "goed op zichzelf" was een latere rationalisering. De meeste politieke innovaties in de geschiedenis zijn bijproducten van machtsstrijd, geen geplande idealen.',
    keyInsight: 'Politieke idealen ontstaan vaak als toevallige bijproducten van heel pragmatische machtsstrategieën.',
    domain: 'history',
    topics: ['democratie', 'oude griekenland', 'politieke oorsprong'],
  },
  {
    format: 'quote',
    hook: '"Een volk dat zijn geschiedenis niet kent, is gedoemd hem te herhalen."',
    body: 'Filosoof George Santayana schreef dit in 1905, maar de zin wordt vrijwel altijd verkeerd begrepen. Santayana bedoelde niet dat kennis van feiten volstaat — hij bedoelde dat een volk dat zijn karakter niet begrijpt dezelfde fouten blijft maken. Historische kennis zonder zelfkennis is nutteloos. De vraag is niet "wat is er gebeurd?" maar "waarom dachten ze dat het een goed idee was?"',
    keyInsight: 'Historische kennis zonder zelfkritisch vermogen biedt geen bescherming tegen herhaling.',
    domain: 'history',
    topics: ['geschiedenisfilosofie', 'santayana', 'collectief geheugen'],
  },
  {
    format: 'question',
    hook: 'Wat als de Industriële Revolutie eerder had kunnen starten?',
    body: 'De oudheid had stoommachines — de aeolipile van Hero van Alexandrië (eerste eeuw n.Chr.) werkte op stoomkracht. Maar hij werd als speelgoed gezien, niet als werktuig. Waarom? Sommige historici wijzen op slavernij: als arbeid gratis is, is er geen prikkel om arbeid te vervangen door machines. Beschikbaarheid van goedkope arbeiders kan technologische innovatie actief remmen.',
    keyInsight: 'Goedkope arbeid remt innovatie — schaarste en hoge lonen zijn soms de beste katalysator voor technologische doorbraken.',
    domain: 'history',
    topics: ['industriële revolutie', 'technologie', 'arbeid'],
  },
  {
    format: 'insight',
    hook: 'Het Mongoolse Rijk was de grootste vrijhandelszone ooit.',
    body: 'Genghis Khan staat bekend om bloedbaden. Minder bekend: zijn rijk creëerde de Pax Mongolica, waarbinnen handelaren van China tot Europa veilig reisden. Mongolische khans tolereerden alle religies, beschermden kooplieden en standardiseerden gewichten en maten. De Zijderoute bereikte zijn hoogtepunt onder Mongools bestuur. Pest reisde langs diezelfde routes mee — ook dat was een gevolg van globalisering avant la lettre.',
    keyInsight: 'De wreedste veroveraars van de geschiedenis creëerden soms ook de meest open en verbonden wereld.',
    domain: 'history',
    topics: ['mongolen', 'handel', 'globalisering'],
  },

  // ── ECONOMICS (17) ───────────────────────────────────────────────────────

  {
    format: 'insight',
    hook: 'Gratis dingen maken mensen meer ontevreden, niet minder.',
    body: 'Gedragseconomen ontdekten dat mensen gratis producten anders waarderen dan goedkope. In één experiment kozen mensen massaal voor een gratis, slechtere chocolade boven een uitstekende chocolade voor één cent. Nul euro activeert een emotionele reactie die rationeel denken overschrijft. Bedrijven die "gratis" aanbieden weten dit: ze winnen gebruikers maar creëren ook de verwachting dat alles altijd gratis zou moeten zijn.',
    keyInsight: 'Gratis verlaagt de gepercipieerde waarde — zowel van het product als van alles wat eromheen bestaat.',
    domain: 'economics',
    topics: ['gedragseconomie', 'prijspsychologie', 'beslissingen'],
  },
  {
    format: 'contrast',
    hook: 'Hogere lonen maken bedrijven minder winstgevend.',
    body: 'Meer loon betekent hogere kosten en lagere winst, zo lijkt het || Henry Ford betaalde in 1914 het dubbele van het marktloon en zag zijn productiviteit exploderen, zijn verloop dalen en zijn afzetmarkt groeien — zijn eigen werknemers kochten zijn auto\'s. Economen noemen dit het efficiëntieloon: boven een bepaald niveau werken hogere lonen als investering, niet als kostenpost. Walmart ontdekte hetzelfde na een loonsverhoging in 2015.',
    keyInsight: 'Loon is niet alleen een kostenpost maar een investering in productiviteit, loyaliteit en vraag.',
    domain: 'economics',
    topics: ['arbeidseconomie', 'lonen', 'bedrijfsstrategie'],
  },
  {
    format: 'story',
    hook: 'Een taxibedrijf maakte chauffeurs armer door hen rijker te laten worden.',
    body: 'Onderzoekers analyseerden Uber-chauffeurs in New York en ontdekten iets vreemds: op regenachtige, drukke dagen — als tarieven piekten — stopten veel chauffeurs eerder met werken. Op rustige dagen bleven ze langer rijden. Waarom? Ze stelden zichzelf een dagelijks inkomensdoel. Eenmaal bereikt, stoppen ze — ook al zouden ze nu meer per uur verdienen. Economisch rationeel op de dag, irrationeel over de week.',
    keyInsight: 'Mensen optimaliseren niet voor het beste resultaat, maar voor het bereiken van een mentaal referentiepunt.',
    domain: 'economics',
    topics: ['gedragseconomie', 'arbeidsmarkt', 'beslissingen'],
  },
  {
    format: 'steelman',
    hook: 'Misschien heeft de Luddiet volledig gelijk over automatisering.',
    body: 'Het standaard economisch argument: technologie vernietigt banen maar creëert er ook nieuwe. Maar dit veronderstelt dat nieuwe banen even toegankelijk zijn voor de mensen wier baan verdwijnt. Een 55-jarige fabrieksmedewerker kan niet makkelijk omscholen naar data-analist. Economen als Daron Acemoglu tonen aan dat automatisering in de VS de loonongelijkheid vergroot heeft. De Luddiet had mogelijk de feiten fout, maar de zorg was terecht.',
    keyInsight: 'Technologische winst op macroniveau kan reële verliezers creëren die nooit compensatie ontvangen.',
    domain: 'economics',
    topics: ['automatisering', 'ongelijkheid', 'technologie'],
  },
  {
    format: 'contrast',
    hook: 'Concurrentie leidt altijd tot betere producten en lagere prijzen.',
    body: 'Meer spelers in een markt zorgt voor innovatie en efficiency || In netwerkindustrieën (sociale media, betaalsystemen) leidt meer concurrentie tot fragmentatie die iedereen schaadt. Economen noemen dit "winner-take-all" markten: hier creëert consolidatie waarde. Regulering die concurrentie forceert in netwerkmarkten kan de totale welvaart verlagen in plaats van verhogen.',
    keyInsight: 'Niet elke markt profiteert van meer concurrentie — netwerkeffecten maken sommige monopolies efficiënter.',
    domain: 'economics',
    topics: ['marktwerking', 'monopolie', 'netwerken'],
  },
  {
    format: 'question',
    hook: 'Waarom werkt schuldkwijtschelding voor arme landen niet zoals gedacht?',
    body: 'Intuïtie zegt: schulden kwijtschelden geeft arme landen ademruimte om te groeien. Maar economen van het IMF ontdekten een verrassend patroon: landen die kwijtschelding kregen, namen daarna snel nieuwe schulden op. Waarom? De verwachting van toekomstige kwijtschelding verlaagt de prikkel om verantwoord te lenen. Dit heet "moral hazard" — het redden van mensen van gevolgen verandert hun toekomstig gedrag.',
    keyInsight: 'Interventies die problemen oplossen, kunnen de prikkels creëren die het probleem in stand houden.',
    domain: 'economics',
    topics: ['ontwikkelingseconomie', 'schulden', 'moral hazard'],
  },
  {
    format: 'story',
    hook: 'Een Peruaanse econoom ontdekte dat wetten armoede kunnen creëren.',
    body: 'Hernando de Soto onderzocht waarom Peruaanse straatverkopers niet konden groeien. Hij liet zijn team uitzoeken hoelang het duurde om legaal een klein bedrijf te registreren: 289 dagen bij full-time inzet en 31 overheidsinstanties. Zijn conclusie: illegale economieën bestaan niet omdat mensen de wet negeren, maar omdat de wet te complex is. Zijn boek "The Mystery of Capital" veranderde hoe ontwikkelingseconomen over eigendomsrechten denken.',
    keyInsight: 'Bureaucratische complexiteit is zelf een economische belemmering die arme mensen het hardst treft.',
    domain: 'economics',
    topics: ['ontwikkelingseconomie', 'eigendomsrechten', 'regulering'],
  },
  {
    format: 'steelman',
    hook: 'Het beste argument voor basisinkomen komt van Milton Friedman.',
    body: 'Friedman, de libertaire held van markteconomen, stelde in 1962 een "negatieve inkomstenbelasting" voor — in wezen een basisinkomen. Zijn argument: alle huidige sociale zekerheid is bureaucratisch inefficiënt, stigmatiserend en arbeidsmarktvertekenend. Een universele directe uitkering is eenvoudiger, goedkoper en respecteert de keuzevrijheid van de ontvanger meer. Conservatieven kunnen basisinkomen steunen, niet ondanks hun principes maar dankzij hen.',
    keyInsight: 'Het sterkste argument voor basisinkomen is niet links-egalitair maar rechts-libertair: eenvoud en keuzevrijheid.',
    domain: 'economics',
    topics: ['basisinkomen', 'sociaal beleid', 'libertarisme'],
  },
  {
    format: 'insight',
    hook: 'Arme mensen zijn betere economische beslissers dan rijke mensen denken.',
    body: 'Econoom Abhijit Banerjee (Nobelprijswinnaar 2019) woonde jaren in sloppenwijken om financieel gedrag te bestuderen. Zijn ontdekking: arme mensen nemen zeer gesofisticeerde risicobeslissingen. Ze spreiden inkomen over meerdere informele microkredieten, beheren liquiditeit met precisie en kiezen bewust voor laagrisicostrategieën. Wat rijke buitenstaanders zien als "irrationele consumptie" is vaak een rationele buffer tegen onzekerheid.',
    keyInsight: 'Armoede is geen gebrek aan intelligentie maar een gebrek aan marge voor fouten — wat rationeel anders gedrag vraagt.',
    domain: 'economics',
    topics: ['armoede', 'gedragseconomie', 'ontwikkeling'],
  },
  {
    format: 'quote',
    hook: '"In the long run we are all dead."',
    body: 'John Maynard Keynes schreef dit in 1923 als kritiek op economen die zeiden dat markten zichzelf op lange termijn herstellen. Zijn punt: "lange termijn" is geen antwoord aan mensen die nu honger lijden. De zin wordt vandaag misbruikt als argument voor korte-termijn denken, maar Keynes bedoelde precies het tegenovergestelde: overheidsbeleid moet ingrijpen voordat het te laat is.',
    keyInsight: 'Theoretisch correcte antwoorden op lange termijn zijn moreel onacceptabel als de pijn nu plaatsvindt.',
    domain: 'economics',
    topics: ['keynesianisme', 'macro-economie', 'beleid'],
  },
  {
    format: 'story',
    hook: 'Een veiling voor visrechten redde een vissoort van uitsterven.',
    body: 'In de jaren negentig dreigde de Canadese kabeljauwstand te crashen. Visecologen smeekten om quota, maar vissers bleven te veel vangen — elk individu had reden om snel te vangen vóór een ander dat deed. Econoom Ragnar Arnason stelde verhandelbare vangstrechten voor. Plotseling hadden vissers belang bij een gezonde visstand, want gezonde vis verhoogde de waarde van hun rechten. Economische prikkels deden wat verboden niet konden.',
    keyInsight: 'Milieuproblematiek is vaak een eigendomsprobleem: als niemand iets bezit, beschermt niemand het.',
    domain: 'economics',
    topics: ['milieueconomie', 'visserij', 'eigendomsrechten'],
  },
  {
    format: 'question',
    hook: 'Maakt meer keuze ons gelukkiger?',
    body: 'Supermarkt Sheetz A/B-testete 6 versus 24 jam-varianten. De grote selectie trok meer aandacht, maar verkocht zeven keer minder. Psycholoog Barry Schwartz noemt dit de "paradox van keuze": meer opties verhogen verwachtingen, vergroten angst voor spijt en verlagen tevredenheid met elke keuze. Rijke maatschappijen met eindeloze opties rapporteren systematisch hogere levels van beslissingsvermoeidheid en keuzeangst.',
    keyInsight: 'Keuzevrijheid boven een bepaalde drempel vermindert welzijn — minder opties kan meer vrijheid voelen.',
    domain: 'economics',
    topics: ['gedragseconomie', 'welzijn', 'beslissingen'],
  },
  {
    format: 'insight',
    hook: 'Corruptie kan economische groei stimuleren in fragiele staten.',
    body: 'Het intuïtieve beeld: corruptie remt altijd economische groei. Maar econoom Pranab Bardhan beschreef landen waarbij corruptie als smeermiddel werkt voor inefficiënte bureaucratie. In landen met extreem trage regulering betaalt een ondernemer steekpenningen om zes maanden te wachten in plaats van tien jaar. Dit is schadelijk op lange termijn, maar verklaart waarom sommige landen groeien ondanks corruptie.',
    keyInsight: 'Corruptie is een symptoom van institutioneel falen — aanpakken van symptomen zonder oorzaken kan contraproductief zijn.',
    domain: 'economics',
    topics: ['institutionele economie', 'corruptie', 'ontwikkeling'],
  },
  {
    format: 'steelman',
    hook: 'Prijsafspraken tussen concurrenten kunnen consumenten soms ten goede komen.',
    body: 'Kartels zijn illegaal en schadelijk. Maar economen beschrijven situaties waar coördinatie anders uitpakt. In de luchtvaart leidde concurrentie tot een "race to the bottom" op veiligheidsuitgaven — branchenormen (een vorm van coördinatie) creëerden hogere standaarden. In farmaceutica maakt patent-pooling medicijnen betaalbaarder. Het probleem is niet coördinatie op zich, maar coördinatie zonder externe controle.',
    keyInsight: 'Samenwerking tussen concurrenten is niet inherent slecht — de sleutel is transparantie en publiek toezicht.',
    domain: 'economics',
    topics: ['concurrentiebeleid', 'marktwerking', 'regulering'],
  },
  {
    format: 'question',
    hook: 'Waarom werkt Cuba\'s gezondheidszorg beter dan verwacht?',
    body: 'Cuba heeft een van de laagste kindersterftecijfers ter wereld — lager dan de VS — ondanks een fractie van de welvaart. Hoe? Preventie boven behandeling: Cuba heeft meer huisartsen per hoofd dan welk land ook. Ze behandelen chronische ziekten vroeg, voor ze duur worden. Economen gebruiken Cuba als casus voor een ongemakkelijke vraag: is gezondheid een kwestie van hoeveel je uitgeeft, of hoe je dat organiseert?',
    keyInsight: 'Preventieve zorg is goedkoper en effectiever dan curatieve zorg — maar politiek moeilijker te financieren.',
    domain: 'economics',
    topics: ['gezondheidszorg', 'preventie', 'ontwikkeling'],
  },
  {
    format: 'contrast',
    hook: 'Rijkere landen hebben meer economische vrijheid dan armere landen.',
    body: 'Welvaart en liberale markteconomie gaan altijd hand in hand || Economisch historicus Ha-Joon Chang toonde aan dat vrijwel alle huidige rijke landen groot werden door protectionisme, staatssteun en industriebeleid — niet door vrije handel. De VS beschermde haar industrie met hoge tarieven in de negentiende eeuw. Zuid-Korea en Japan kopieerden technologie achter hoge muren. Ze prediken nu vrije handel, nadat ze er zelf niet van afhingen.',
    keyInsight: 'Rijke landen bereikten welvaart met protectionisme en trekken de ladder omhoog zodra ze bovenaan staan.',
    domain: 'economics',
    topics: ['handelspolitiek', 'protectionisme', 'ontwikkeling'],
  },
  {
    format: 'steelman',
    hook: 'Het sterkste argument om belasting op erfenissen te verbieden.',
    body: 'Erfbelasting lijkt rechtvaardig: het remt dynastieke rijkdom. Maar libertaire economen wijzen op een paradox: erfbelasting ontmoedigt rijke ouders om te sparen en te investeren, want hun erfenis zal worden belast. Ze consumeren liever. Dit remt kapitaalaccumulatie en productieve investeringen die de hele economie ten goede komen. Bovendien treft erfbelasting familiebedrijven die liquide middelen moeten verkopen om belasting te betalen.',
    keyInsight: 'Belastingen op vermogensoverdracht kunnen de kapitaalvorming remmen die economische groei voedt.',
    domain: 'economics',
    topics: ['belastingbeleid', 'vermogensongelijkheid', 'erfenissen'],
  },

  // ── PHILOSOPHY (16) ──────────────────────────────────────────────────────

  {
    format: 'question',
    hook: 'Als je alles van iemand vervangt, is het dan nog dezelfde persoon?',
    body: 'Het schip van Theseus: als je elke plank van een schip vervangt, is het nog hetzelfde schip? Nu toepassen op jezelf: de atomen in je lichaam worden binnen zeven jaar volledig vervangen. Je herinneringen veranderen elke keer je ze ophaalt. Je waarden van tien jaar geleden zijn misschien vreemd voor je nu. Filosofen vragen: wat maakt jij "jij"? Continuïteit van geheugen? Lichaam? Karakter? Geen antwoord is vanzelfsprekend.',
    keyInsight: 'Persoonlijke identiteit is geen gegeven maar een filosofisch probleem dat ons zelfbegrip fundamenteel beïnvloedt.',
    domain: 'philosophy',
    topics: ['identiteit', 'metafysica', 'persoonlijkheid'],
  },
  {
    format: 'steelman',
    hook: 'Het sterkste argument voor eten wat je wilt, komt van een filosoof.',
    body: 'Peter Singer stelt dat we moreel verplicht zijn dierenleed te minimaliseren, wat zou leiden tot veganisme. Maar filosoof Roger Scruton repliceerde: lokale, vrije-uitloopveehouderij creëert een ecosysteem waarbij dieren bestaan dankzij menselijk gebruik. Zonder dat gebruik bestaat het dier niet. De vraag verschuift: is een goed geleefd kort leven moreel beter dan nooit leven? Scruton\'s argument is niet gemakkelijk te weerleggen.',
    keyInsight: 'Ethische conclusies veranderen drastisch afhankelijk van welk referentiepunt je kiest voor vergelijking.',
    domain: 'philosophy',
    topics: ['dierethiek', 'morele filosofie', 'voedselethiek'],
  },
  {
    format: 'insight',
    hook: 'Socrates schreef nooit één zin op — en dat was geen toeval.',
    body: 'Alles wat we van Socrates weten, komt via anderen — voornamelijk Plato. Socrates schreef bewust niets op. Hij geloofde dat het geschreven woord het denken beschadigt: een tekst kan zichzelf niet verdedigen, kan niet antwoorden op vragen en geeft de schijn van begrip zonder het echte begrip. Hij noemde dit de "farmakon"-paradox — schrijven is zowel medicijn als gif voor het denken. Ironisch genoeg weten we dit alleen doordat Plato het opschreef.',
    keyInsight: 'De meest doordachte communicatie lokt een dialoog uit; ze sluit geen monoloog af.',
    domain: 'philosophy',
    topics: ['socrates', 'kennistheorie', 'communicatie'],
  },
  {
    format: 'contrast',
    hook: 'Stoïcijnen waren emotieloze, koele denkers die niet voelden.',
    body: 'Stoïcijnen onderdrukten alle emoties en streefden naar onverschilligheid || Stoïcijnen maakten een cruciaal onderscheid: ze wilden niet gevoelloos zijn, maar vrij zijn van emoties die buiten hun controle liggen. Marcus Aurelius huilde om zijn gestorven kinderen. Het verschil: hij liet zijn verdriet niet dicteren door externe omstandigheden. Stoïcisme is geen koelheid, maar de kunst om te kiezen welke emoties je toelaat jou te sturen.',
    keyInsight: 'Stoïcisme is niet de afwezigheid van gevoel maar de weigering om je door oncontroleerbare zaken te laten leiden.',
    domain: 'philosophy',
    topics: ['stoïcisme', 'emoties', 'antieke filosofie'],
  },
  {
    format: 'quote',
    hook: '"Hell is other people."',
    body: 'Jean-Paul Sartre schreef dit in zijn toneelstuk "Huis Clos" (1944). Maar hij bedoelde niet dat mensen verschrikkelijk zijn. Zijn punt: we kunnen onszelf nooit volledig zien — we zijn afhankelijk van hoe anderen ons zien om onszelf te begrijpen. Die afhankelijkheid van de blik van de ander is een fundamentele existentiële spanning. De hel is niet dat anderen vervelend zijn, maar dat we hen nodig hebben om te weten wie we zijn.',
    keyInsight: 'We construeren ons zelfbegrip mede door de blik van anderen — dat geeft hen macht die we niet kunnen vermijden.',
    domain: 'philosophy',
    topics: ['sartre', 'existentialisme', 'intersubjectiviteit'],
  },
  {
    format: 'story',
    hook: 'Eén trolleyprobleem veranderde hoe juristen over moord nadenken.',
    body: 'Filosoof Judith Jarvis Thomson bedacht een variant: een chirurg heeft vijf stervende patiënten die elk één orgaan nodig hebben. Eén gezonde patiënt heeft alle benodigde organen. Mag de chirurg die ene doden om vijf te redden? De meeste mensen zeggen nee — maar waarom? Hetzelfde getal mensen is betrokken als in het klassieke trolleyprobleem. Haar analyse onthulde een moreel verschil tussen schade als middel versus schade als neveneffect.',
    keyInsight: 'Het morele verschil tussen "gebruiken als middel" en "toestaan als neveneffect" structureert ons recht dieper dan we denken.',
    domain: 'philosophy',
    topics: ['morele filosofie', 'gedachte-experimenten', 'recht'],
  },
  {
    format: 'insight',
    hook: 'Vrijheid van wil is misschien een nuttige illusie, geen feit.',
    body: 'Neurowetenschapper Benjamin Libet mat in 1983 hersenactiviteit bij beslissingen. Zijn bevinding: de hersenen initiëren een beweging 350 milliseconden voor je je bewust bent van de beslissing. Je brein beslist; jij "ervaart" het als jouw keuze. Filosoof Daniel Dennett repliceerde: bewustzijn is geen moment maar een stroom. Maar het debat blijft: als besluiten neurofysisch voorafgaan aan bewustzijn, wat betekent dan persoonlijke verantwoordelijkheid?',
    keyInsight: 'De vraag of vrije wil bestaat heeft directe implicaties voor hoe we schuld en straf begrijpen.',
    domain: 'philosophy',
    topics: ['vrije wil', 'neurofilosofie', 'verantwoordelijkheid'],
  },
  {
    format: 'question',
    hook: 'Kun je weten of jij niet de enige bewuste persoon bent?',
    body: 'Het "probleem van andere geesten": jij weet direct dat jij bewust bent. Maar hoe weet je dat anderen ook daadwerkelijk bewust zijn, en niet puur mechanisch gedrag vertonen? Filosoof David Chalmers beschreef "filosofische zombies" — wezens die identiek gedrag vertonen maar geen innerlijk bewustzijn hebben. Er is geen logisch bewijs dat anderen niet zulke zombies zijn. De meesten geloven in andermans bewustzijn op basis van analogie, niet bewijs.',
    keyInsight: 'Onze diepste sociale aanname — dat anderen bewust zijn — rust niet op bewijs maar op geloof gebaseerd op gelijkenis.',
    domain: 'philosophy',
    topics: ['bewustzijn', 'andere geesten', 'kennistheorie'],
  },
  {
    format: 'steelman',
    hook: 'Het beste filosofische argument om nooit te stemmen.',
    body: 'Als jouw stem statistisch nooit het verschil maakt in een nationale verkiezing — wat wiskundig vrijwel zeker is — is stemmen rationeel bezien weggegooid. Filosoof Jason Brennan gaat verder: als de meeste kiezers slecht geïnformeerd zijn, schaadt massastemmen de kwaliteit van beslissingen. Het tegenargument is symbolisch of collectief — maar Brennan repliceert: collectieve symboliek rechtvaardigt individuele rationele kosten niet. Dit argument is lastig te weerleggen zonder van terrein te veranderen.',
    keyInsight: 'Democratie werkt niet goed als argument voor individueel stemmen — het vraagt om collectieve en morele, niet rationele, rechtvaardiging.',
    domain: 'philosophy',
    topics: ['democratie', 'rationaliteit', 'politieke filosofie'],
  },
  {
    format: 'contrast',
    hook: 'Nietzsche was nihilist die geloofde dat niets betekenis heeft.',
    body: 'Nietzsche verkondigde dat het leven zinloos is en we dat maar moeten accepteren || Nietzsche waarschuwde juist tegen nihilisme als het grootste gevaar van zijn tijd. "God is dood" betekende: de oude bronnen van betekenis zijn weggevallen, en nu moeten mensen actief nieuwe waarden scheppen. De Übermensch is geen wreedaard maar iemand die de moed heeft eigen waarden te creëren in plaats van te lenen. Nietzsche was een filosoof van betekenis, niet van zinloosheid.',
    keyInsight: 'Nietzsche beschreef het nihilisme als crisis, niet als oplossing — zijn werk is een oproep tot actieve betekeniscreatie.',
    domain: 'philosophy',
    topics: ['nietzsche', 'nihilisme', 'waarden'],
  },
  {
    format: 'quote',
    hook: '"De ononderzochte plek is het leven niet waard."',
    body: 'Socrates sprak dit volgens Plato op zijn rechtszaak, kort voor zijn doodsvonnis. Hij bedoelde: een leven zonder zelfreflectie, zonder het bevragen van je aannames en waarden, is kwalitatief niet anders dan dat van een dier. Het is een radicale claim — dat denken een morele plicht is, geen luxe. Vandaag zouden we kunnen vragen: is doomscrolling zonder nadenken een modern equivalent van het ononderzochte leven?',
    keyInsight: 'Zelfreflectie is geen hobby maar een morele verplichting — bewust leven vereist actieve mentale inspanning.',
    domain: 'philosophy',
    topics: ['socrates', 'zelfreflectie', 'levensfilosofie'],
  },
  {
    format: 'story',
    hook: 'Kant verliet nooit zijn stad — en schreef de kern van westerse filosofie.',
    body: 'Kant verliet Königsberg vrijwel nooit in zijn leven. Zijn dagelijkse wandeling was zo stipt dat buren hun klokken gelijk zetten. Op zijn zeventigste las hij Hume en schreef dat hij "uit zijn dogmatische slaap gewekt" was. Daarna produceerde hij drie Kritieken die nog steeds de kern vormen van westerse filosofie. Zijn inzicht: we kennen de wereld nooit direct, maar alleen gefilterd door onze mentale structuren.',
    keyInsight: 'Onze geest structureert de werkelijkheid die we waarnemen — we zijn nooit neutrale observatoren van de wereld.',
    domain: 'philosophy',
    topics: ['kant', 'kennistheorie', 'verlichting'],
  },
  {
    format: 'insight',
    hook: 'Taal bepaalt niet wat je kunt denken, maar hoe makkelijk je het kunt denken.',
    body: 'De Sapir-Whorf hypothese in sterke vorm — taal bepaalt gedachte — is wetenschappelijk weerlegd. Maar de zwakke versie blijft interessant: talen met meer sneeuwwoorden maken onderscheiden sneewtypes cognitief toegankelijker. Russisch sprekers, die twee woorden voor blauw hebben, detecteren blauwverschillen sneller. Taal is geen kooi maar een infrastructuur — het maakt bepaalde gedachten gladder en andere ruwer.',
    keyInsight: 'Taal vormt niet de grenzen van ons denken maar de weerstand — sommige gedachten kosten meer moeite in sommige talen.',
    domain: 'philosophy',
    topics: ['taalfilosofie', 'cognitie', 'sapir-whorf'],
  },
  {
    format: 'quote',
    hook: '"Wij zijn allemaal de blinden die een olifant beschrijven."',
    body: 'Dit is een parafrase van een boeddhistisch verhaal dat dichter Rumi gebruikte in de dertiende eeuw. Blinde mannen voelen elk een deel van een olifant: "een slang" (slurf), "een muur" (zij), "een touw" (staart). Elk heeft gelijk over hun deel; niemand heeft gelijk over het geheel. Filosofen gebruiken dit als metafoor voor hoe alle menselijke kennis partieel is — inclusief wetenschappelijke theorieën die slechts één hoek belichten.',
    keyInsight: 'Alle menselijke kennis is perspectivistisch — het erkennen van blinde vlekken is een voorwaarde voor wijsheid.',
    domain: 'philosophy',
    topics: ['epistemologie', 'perspectivisme', 'boeddhisme'],
  },
  {
    format: 'story',
    hook: 'Eén gedachte-experiment over een sluier veranderde de politieke filosofie.',
    body: 'In 1971 publiceerde John Rawls zijn "Theory of Justice." Zijn centrale gedachte: stel je voor dat je de regels van een samenleving mag opstellen, maar je weet niet welke plek je erin zult innemen — rijk of arm, gezond of ziek. Achter deze "sluier van onwetendheid" zullen mensen rechtvaardige regels kiezen, omdat ze zelf in elke positie terecht kunnen komen. Dit "veil of ignorance" werd het invloedrijkste argument voor sociale rechtvaardigheid van de twintigste eeuw.',
    keyInsight: 'Rechtvaardigheid is wat je zou kiezen als je niet wist welke plek je in de samenleving zou innemen.',
    domain: 'philosophy',
    topics: ['rechtvaardigheid', 'rawls', 'politieke filosofie'],
  },
  {
    format: 'steelman',
    hook: 'Het sterkste argument voor absolute leugenverbod, ook om levens te redden.',
    body: 'Kant beweerde dat liegen altijd verkeerd is — zelfs als een moordenaar vraagt waar je vriend zich verbergt. Dat klinkt absurd. Maar zijn argument: als jij liegt om goed te doen, neem je de verantwoordelijkheid voor gevolgen die je niet kunt kennen. Misschien ontsnapt je vriend al, en geeft jouw leugen de moordenaar een alibi. Door te liegen verander je de morele keten met onvoorziene gevolgen. Eerlijkheid schept een voorspelbare morele wereld.',
    keyInsight: 'Absolute regels vermijden cognitieve corruptie en onvoorziene gevolgen — situationeel redeneren heeft zijn eigen gevaren.',
    domain: 'philosophy',
    topics: ['kant', 'deontologie', 'liegen'],
  },
]

export default SEED_CARDS
